platform :ios, '9.0'

target 'example' do
  #use_frameworks!

  pod 'React', :path => '../../../rn-lib/node_modules/react-native', :subspecs => [
   'Core',
   'ART',
   'CxxBridge',
   'DevSupport',
   'RCTText',
   'RCTNetwork',
   'RCTWebSocket',
   'RCTAnimation',
   'RCTPushNotification',
   'RCTSettings',
   'RCTLinkingIOS',
   'RCTBlob',
   'RCTActionSheet',
   'RCTGeolocation',
   'RCTImage',
   'RCTVibration',
   'RCTCameraRoll',
  ]
  
  pod 'yoga', :path => '../../../rn-lib/node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../../../rn-lib/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../../rn-lib/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../../rn-lib/node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNGestureHandler', :path => '../../../rn-lib/node_modules/react-native-gesture-handler'
  pod 'react-native-ftp-jm', :podspec => '../../../rn-lib/node_modules/react-native-ftp-jm/react-native-ftp-jm.podspec'

  target 'example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

