platform :ios, '9.0'

target 'RNReactNativeFtpJm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
  pod 'JMSmartFTPUtils', '1.0.2'
  pod 'CocoaAsyncSocket', '~> 7.6.5'

  pod 'React', :path => '../../rn-lib/node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport', 
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', 
    'RCTAnimation'
  ]
  pod 'yoga', :path => '../../rn-lib/node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../../rn-lib/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../rn-lib/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../rn-lib/node_modules/react-native/third-party-podspecs/Folly.podspec'

end

